#!/bin/bash

BASE_DIR=$(dirname $0)
source $BASE_DIR/common

if [ $# -ne 1 ]; then
    echo "$(basename $0) <firmware-file>"
    exit 1
fi

set -x
openocd $ocd_args \
        -c "set IMAGE_FILE $1" \
        -f $BASE_DIR/ocd-flash.cfg
